"""
Jira integration — builds Jira issue JSON.
Mock by default; POST if JIRA_* env vars are set.
"""
from __future__ import annotations

import os
from typing import Any, Dict, List, Optional

from ...attacks.knowledge_graph import get_remediation_playbooks


def _adf_doc(text: str) -> Dict[str, Any]:
    """Jira Cloud REST v3 requires description as Atlassian Document Format."""
    paragraphs = [line.strip() for line in text.strip().splitlines() if line.strip()]
    if not paragraphs:
        paragraphs = ["M8 security finding"]
    return {
        "type": "doc",
        "version": 1,
        "content": [
            {
                "type": "paragraph",
                "content": [{"type": "text", "text": line[:2000]}],
            }
            for line in paragraphs[:40]
        ],
    }


def build_jira_issue(
    run_id: str,
    attack_id: str,
    category: str,
    severity: str,
    reason: str,
    mitre_tags: List[str],
    remediation_ids: List[str],
    transcript_summary: str,
) -> Dict[str, Any]:
    """Build a Jira issue JSON payload."""
    project_key = os.getenv("JIRA_PROJECT_KEY", "SEC")

    remediation_texts = get_remediation_playbooks(remediation_ids)
    remediation_section = "\n".join(
        f"* *{rid}*: {text}" for rid, text in remediation_texts.items()
    )
    mitre_section = ", ".join(f"[{m}|https://atlas.mitre.org/techniques/{m}]" for m in mitre_tags)

    owasp_map = {
        "direct_injection": "LLM01: Prompt Injection",
        "indirect_injection": "LLM01: Prompt Injection + LLM07: Insecure Plugin Design",
        "tool_misuse": "LLM08: Excessive Agency",
        "exfiltration": "LLM06: Sensitive Information Disclosure",
        "multilingual": "LLM01: Prompt Injection (Multilingual Evasion)",
        "obfuscated": "LLM01: Prompt Injection (Obfuscated)",
    }
    owasp_ref = owasp_map.get(category, "LLM01: Prompt Injection")

    description = f"""
h2. Security Finding — M8 Assessment

*Run ID:* {run_id}
*Attack ID:* {attack_id}
*Category:* {category}
*Severity:* {severity}
*OWASP Agentic Risk:* {owasp_ref}
*MITRE ATLAS Techniques:* {mitre_section or 'N/A'}

h3. Finding Details
{reason}

h3. Evidence Summary
{transcript_summary[:500]}

h3. Remediation Steps
{remediation_section or 'Apply prompt injection mitigations and implement a policy broker.'}

h3. Notes
* All data in this report is SIMULATED DEMO DATA.
* Generated by M8 — Adaptive Red-Team Testing for AI Agents (SCD 2026).
"""

    return {
        "fields": {
            "project": {"key": project_key},
            "summary": f"[M8] {severity} — {attack_id}: {category} attack succeeded",
            "description": _adf_doc(description),
            "issuetype": {"name": os.getenv("JIRA_ISSUE_TYPE", "Task")},
            "labels": ["m8", "security", "ai-agent", category],
        },
        "_mock": True,
        "_run_id": run_id,
        "_attack_id": attack_id,
    }


async def send_jira(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Create Jira issue. Mock if env vars not configured."""
    base_url = os.getenv("JIRA_BASE_URL", "")
    user_email = os.getenv("JIRA_USER_EMAIL", "")
    api_token = os.getenv("JIRA_API_TOKEN", "")

    if not all([base_url, user_email, api_token]):
        return {
            "status": "mock",
            "message": "JIRA_* env vars not set — issue stored as mock",
            "payload": payload,
        }

    try:
        import httpx
        import base64
        creds = base64.b64encode(f"{user_email}:{api_token}".encode()).decode()
        headers = {
            "Authorization": f"Basic {creds}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        outbound_payload = {"fields": payload["fields"]}
        async with httpx.AsyncClient(timeout=15) as client:
            resp = await client.post(
                f"{base_url.rstrip('/')}/rest/api/3/issue",
                json=outbound_payload,
                headers=headers,
            )
            try:
                resp_data = resp.json()
            except Exception:
                resp_data = {"body": resp.text[:400]}
            if resp.status_code >= 400:
                return {
                    "status": "error",
                    "issue_key": resp_data.get("key"),
                    "http_status": resp.status_code,
                    "message": str(resp_data)[:500],
                }
            return {
                "status": "created",
                "issue_key": resp_data.get("key", "N/A"),
                "http_status": resp.status_code,
            }
    except Exception as e:
        return {
            "status": "error",
            "message": str(e),
            "payload": payload,
        }
